### ISSUE TITLE
Add dummy dependencies

### ISSUE THREAD

**Issue by kossnocorp** [kossnocorp/genotype#19]
Add the ability to define and resolve project dependencies. It will create a foundation for further extension and fully-fledged modules. I need this to consume #18 from another Genotype project.

The dependencies will look something like that:

```toml
name = "mindcontrol-types"

# ...

[dependencies]
 
genotype_source_json = { dummy = { ts = "@mindcontrol/types", py = "mindcontrol_types", rs = "mindcontrol_types" } }
```

It will make external dependencies work, i.e.: 

```type
use genotype_source_json/GtjNull

Hello = GtjNull
```
